
-- Generated by ORDS REST Data Services 21.3.2.r3271419
-- Schema: STRAVA  Date: Tue Jan 11 10:43:07 2022 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaActivityDistance',
      p_base_path      => '/sdw/charts/StravaActivityDistance/',
      p_items_per_page => 0,
      p_status         => 'PUBLISHED',
      p_comments       => 'how long did we go for');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaActivityDistance',
      p_pattern        => 'settings',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaActivityDistance',
      p_pattern        => 'settings',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
	''application/json'' AS CONTENT_TYPE,
	TO_CLOB( ''{
    "com.oracle.dbtools.chart": [
        {
            "orientation": "vertical",
            "sorting": "off",
            "coordinateSystem": "polar",
            "xAxisTitle": "",
            "yAxisTitle": "",
            "type": "bar",
            "mapping": {
                "groupId": "activity_type",
                "value": "sum(distance)"
            },
            "customOptions": {}
        }
    ]
}'' ) AS BODY,
	''chart_settings.json'' AS FILE_NAME
FROM
	DUAL');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaActivityDistance',
      p_pattern        => 'data/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaActivityDistance',
      p_pattern        => 'data/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select sum(DISTANCE), activity_type
from ACTIVITIES
group by ACTIVITY_TYPE
having sum(distance) > 2
');

    
        
COMMIT;

END;
/


-- Generated by ORDS REST Data Services 21.3.2.r3271419
-- Schema: STRAVA  Date: Tue Jan 11 10:43:49 2022 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaActivityType',
      p_base_path      => '/sdw/charts/StravaActivityType/',
      p_items_per_page => 0,
      p_status         => 'PUBLISHED',
      p_comments       => 'counts by type of activity done');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaActivityType',
      p_pattern        => 'data/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaActivityType',
      p_pattern        => 'data/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select count(*), activity_type from ACTIVITIES
group by ACTIVITY_TYPE
having count(*) > 5
order by 1 desc');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaActivityType',
      p_pattern        => 'settings',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaActivityType',
      p_pattern        => 'settings',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
	''application/json'' AS CONTENT_TYPE,
	TO_CLOB( ''{
    "com.oracle.dbtools.chart": [
        {
            "orientation": "horizontal",
            "sorting": "off",
            "coordinateSystem": "cartesian",
            "xAxisTitle": "",
            "yAxisTitle": "",
            "type": "bar",
            "mapping": {
                "groupId": "activity_type",
                "value": "count(*)"
            },
            "customOptions": {}
        }
    ]
}'' ) AS BODY,
	''chart_settings.json'' AS FILE_NAME
FROM
	DUAL');

    
        
COMMIT;

END;
/


-- Generated by ORDS REST Data Services 21.3.2.r3271419
-- Schema: STRAVA  Date: Tue Jan 11 10:44:07 2022 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaDayOfWeek',
      p_base_path      => '/sdw/charts/StravaDayOfWeek/',
      p_items_per_page => 0,
      p_status         => 'PUBLISHED',
      p_comments       => 'count of activities by day ');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaDayOfWeek',
      p_pattern        => 'settings',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaDayOfWeek',
      p_pattern        => 'settings',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
	''application/json'' AS CONTENT_TYPE,
	TO_CLOB( ''{
    "com.oracle.dbtools.chart": [
        {
            "orientation": "vertical",
            "sorting": "off",
            "coordinateSystem": "cartesian",
            "xAxisTitle": "",
            "yAxisTitle": "",
            "type": "bar",
            "mapping": {
                "groupId": "day_of_week",
                "value": "count(*)"
            },
            "customOptions": {}
        }
    ]
}'' ) AS BODY,
	''chart_settings.json'' AS FILE_NAME
FROM
	DUAL');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaDayOfWeek',
      p_pattern        => 'data/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaDayOfWeek',
      p_pattern        => 'data/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select count(*), to_char(to_date(activity_date,''MON DD, YYYY HH:MI:SS AM''),''MM/DD'') day_of_week
from ACTIVITIES
group by to_char(to_date(activity_date,''MON DD, YYYY HH:MI:SS AM''),''MM/DD'')
order by 2 desc');

    
        
COMMIT;

END;
/


-- Generated by ORDS REST Data Services 21.3.2.r3271419
-- Schema: STRAVA  Date: Tue Jan 11 10:44:25 2022 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaHeartRateType',
      p_base_path      => '/sdw/charts/StravaHeartRateType/',
      p_items_per_page => 0,
      p_status         => 'PUBLISHED',
      p_comments       => 'avg heart rate by type of activity');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaHeartRateType',
      p_pattern        => 'data/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaHeartRateType',
      p_pattern        => 'data/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select avg(AVERAGE_HEART_RATE), activity_type
from ACTIVITIES
group by ACTIVITY_TYPE');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaHeartRateType',
      p_pattern        => 'settings',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaHeartRateType',
      p_pattern        => 'settings',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
	''application/json'' AS CONTENT_TYPE,
	TO_CLOB( ''{
    "com.oracle.dbtools.chart": [
        {
            "orientation": "vertical",
            "sorting": "off",
            "coordinateSystem": "cartesian",
            "xAxisTitle": "",
            "yAxisTitle": "avg heart rate",
            "type": "line",
            "mapping": {
                "groupId": "activity_type",
                "value": "avg(average_heart_rate)"
            },
            "customOptions": {}
        }
    ]
}'' ) AS BODY,
	''chart_settings.json'' AS FILE_NAME
FROM
	DUAL');

    
        
COMMIT;

END;
/


-- Generated by ORDS REST Data Services 21.3.2.r3271419
-- Schema: STRAVA  Date: Tue Jan 11 10:44:41 2022 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaSumTime',
      p_base_path      => '/sdw/charts/StravaSumTime/',
      p_items_per_page => 0,
      p_status         => 'PUBLISHED',
      p_comments       => 'how much time spent per');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaSumTime',
      p_pattern        => 'settings',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaSumTime',
      p_pattern        => 'settings',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
	''application/json'' AS CONTENT_TYPE,
	TO_CLOB( ''{
    "com.oracle.dbtools.chart": [
        {
            "type": "pie",
            "mapping": {
                "groupId": "",
                "seriesId": "activity_type",
                "value": "sum(elapsed_time)"
            },
            "customOptions": {
                "effect3D": "on"
            }
        }
    ]
}'' ) AS BODY,
	''chart_settings.json'' AS FILE_NAME
FROM
	DUAL');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaSumTime',
      p_pattern        => 'data/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaSumTime',
      p_pattern        => 'data/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select sum(elapsed_time), activity_type
from ACTIVITIES
group by ACTIVITY_TYPE');

    
        
COMMIT;

END;
/


-- Generated by ORDS REST Data Services 21.3.2.r3271419
-- Schema: STRAVA  Date: Tue Jan 11 10:45:02 2022 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaHeartRate',
      p_base_path      => '/sdw/charts/StravaHeartRate/',
      p_items_per_page => 0,
      p_status         => 'PUBLISHED',
      p_comments       => 'Strava Heart Rate Chart');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaHeartRate',
      p_pattern        => 'data/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaHeartRate',
      p_pattern        => 'data/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT to_char(to_date(activity_date,''MON DD, YYYY HH:MI:SS AM''),''MM/DD HH:MI'') Day, to_number(AVERAGE_HEART_RATE)
from ACTIVITIES
where to_date(activity_date,''MON DD, YYYY HH:MI:SS AM'') > sysdate - 329
order by activity_date asc');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.chart.StravaHeartRate',
      p_pattern        => 'settings',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.chart.StravaHeartRate',
      p_pattern        => 'settings',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
	''application/json'' AS CONTENT_TYPE,
	TO_CLOB( ''{
    "com.oracle.dbtools.chart": [
        {
            "orientation": "vertical",
            "sorting": "off",
            "coordinateSystem": "cartesian",
            "xAxisTitle": "",
            "yAxisTitle": "",
            "type": "area",
            "mapping": {
                "groupId": "day",
                "value": "to_number(average_heart_rate)"
            },
            "customOptions": {}
        }
    ]
}'' ) AS BODY,
	''chart_settings.json'' AS FILE_NAME
FROM
	DUAL');

    
        
COMMIT;

END;
/
